import os

DEFAULT_DB_PATH = "DELETE_ME_JANGLE_BANKING_DB_PATH_NOT_SET.db"
DB_JANGLE_BANKING_PATH = os.getenv("DB_JANGLE_BANKING_PATH", DEFAULT_DB_PATH)
BATCH_SIZE = int(os.getenv("DB_JANGLE_BANKING_BATCH_SIZE", "100"))
